import os
from datetime import date

from helpers import PROMPTS_ENV, STALE_AGE_DAYS, parse_source_date, today_utc
from langchain_core.messages import HumanMessage, SystemMessage
from state import AgentState

INA_VERSION = os.environ.get("INA_VERSION", "unknown")


def _age_label(published_date: str, today: str) -> str:
    """Human-readable recency annotation for a WEB CONTEXT entry.

    Doing the day-count arithmetic here — rather than leaving it to the
    model — closes off the failure mode where a report cites a source's
    actual publish date but gets the "how stale is this" judgment wrong (or,
    worse, doesn't attempt it and just presents the source as current).
    """
    published = parse_source_date(published_date)
    if published is None:
        return (
            "unknown — the search provider did not return a verifiable "
            "publish date for this source; do not attribute a specific "
            "date to it, and do not treat it as confirmed-current evidence"
        )
    age_days = (date.fromisoformat(today) - published).days
    formatted = published.strftime("%b %-d, %Y")
    if age_days <= 7:
        return f"{formatted} ({age_days}d ago)"
    if age_days <= STALE_AGE_DAYS:
        return f"{formatted} ({age_days}d ago — not last-week news; confirm it's still new information, not a restated fact)"
    if age_days <= 365:
        return f"{formatted} ({age_days}d ago — STALE; do not present as current evidence for a live or fast-moving claim)"
    years = age_days / 365
    return f"{formatted} ({years:.1f} years ago — STALE; background/historical only, must not be cited as current)"


def build_market_analyst_node(llm, system_prompt: str):
    def market_analyst_node(state: AgentState) -> AgentState:
        today = today_utc()
        snippets_text = "\n\n---\n\n".join(state["snippets"])
        context_parts = [
            f"**Query:** {r['query']}\n**Source:** {r['url']}\n"
            f"**Published:** {_age_label(r.get('published_date', ''), today)}\n{r['content']}"
            for r in state["search_results"]
        ]
        context_text = "\n\n---\n\n".join(context_parts)
        prompt = PROMPTS_ENV.get_template("market_analyst.j2").render(
            today=today,
            snippets_text=snippets_text,
            context_text=context_text,
        )
        response = llm.invoke([SystemMessage(content=system_prompt), HumanMessage(content=prompt)])
        report_md = (
            f"# Investment News Analysis AI — {today}\n\n"
            f"{response.content.strip()}\n\n"
            f"---\n*Generated by Investment News Analysis AI v{INA_VERSION}*"
        )
        return {**state, "report": report_md}

    return market_analyst_node
