import os
import warnings
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import TypedDict

import boto3
import jinja2
import markdown
from weasyprint import HTML

# LangGraph instantiates JsonPlusSerializer without allowed_objects; suppress
# the pending deprecation until LangGraph fixes it upstream.
warnings.filterwarnings("ignore", message=r"The default value of `allowed_objects`")

INA_VERSION = os.environ.get("INA_VERSION", "unknown")

_PROMPTS_ENV = jinja2.Environment(
    loader=jinja2.FileSystemLoader(Path(__file__).parent / "prompts"),
    keep_trailing_newline=True,
    undefined=jinja2.StrictUndefined,
)


def _today_utc() -> str:
    override = os.environ.get("INA_DATETIME_OVERRIDE")
    if override:
        return override[:10]
    return datetime.now(tz=timezone.utc).date().isoformat()


# ---------------------------------------------------------------------------
# AWS clients — reused across warm invocations
# ---------------------------------------------------------------------------

_ssm = boto3.client("ssm", region_name=os.environ["AWS_REGION_NAME"])
_s3 = boto3.client("s3", region_name=os.environ["AWS_REGION_NAME"])

INPUT_BUCKET = os.environ["AWS_S3_INPUT_BUCKET_NAME"]
OUTPUT_BUCKET = os.environ["AWS_S3_OUTPUT_BUCKET_NAME"]
SSM_OPENROUTER_PARAM = os.environ["SSM_OPENROUTER_PARAM"]
SSM_TAVILY_PARAM = os.environ["SSM_TAVILY_PARAM"]


def _get_secret(param_name: str) -> str:
    resp = _ssm.get_parameter(Name=param_name, WithDecryption=True)
    return resp["Parameter"]["Value"]


# ---------------------------------------------------------------------------
# S3 helpers
# ---------------------------------------------------------------------------


def _list_snippets(day: str) -> list[str]:
    """Return the text content of every snippet file for the given day (YYYY-MM-DD)."""
    prefix = f"input/{day}/"
    paginator = _s3.get_paginator("list_objects_v2")
    keys = [
        obj["Key"]
        for page in paginator.paginate(Bucket=INPUT_BUCKET, Prefix=prefix)
        for obj in page.get("Contents", [])
    ]
    texts = []
    for key in keys:
        body = _s3.get_object(Bucket=INPUT_BUCKET, Key=key)["Body"].read().decode("utf-8")
        texts.append(body.strip())
    return texts


def _upload_report(day: str, md_text: str, pdf_bytes: bytes) -> None:
    _s3.put_object(
        Bucket=OUTPUT_BUCKET,
        Key=f"output/{day}/report.md",
        Body=md_text.encode("utf-8"),
        ContentType="text/markdown",
    )
    _s3.put_object(
        Bucket=OUTPUT_BUCKET,
        Key=f"output/{day}/report.pdf",
        Body=pdf_bytes,
        ContentType="application/pdf",
    )


# ---------------------------------------------------------------------------
# PDF rendering
# ---------------------------------------------------------------------------

_PDF_CSS = """
body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; color: #222; }
h1 { color: #1a3a5c; border-bottom: 2px solid #1a3a5c; padding-bottom: 6px; }
h2 { color: #2c5f8a; margin-top: 2em; }
h3 { color: #3a7ab8; }
code { background: #f4f4f4; padding: 2px 4px; border-radius: 3px; }
blockquote { border-left: 4px solid #ccc; margin-left: 0; padding-left: 16px; color: #555; }
"""


def _md_to_pdf(md_text: str) -> bytes:
    html_body = markdown.markdown(md_text, extensions=["tables", "fenced_code"])
    full_html = f"<html><head><style>{_PDF_CSS}</style></head><body>{html_body}</body></html>"
    return HTML(string=full_html).write_pdf()


# ---------------------------------------------------------------------------
# No-snippets fallback report
# ---------------------------------------------------------------------------


def _no_snippets_report(day: str) -> str:
    return (
        f"# Investment News Analysis AI — {day}\n\n"
        f"## No Snippets Submitted\n\n"
        f"No news snippets were submitted for {day}. The analysis pipeline was skipped.\n\n"
        f"Please submit at least one news snippet via the web interface before 12:00 UTC\n"
        f"to receive a market analysis report for that day.\n\n"
        f"---\n*Generated by Investment News Analysis AI v{INA_VERSION}*"
    )


# ---------------------------------------------------------------------------
# LangGraph pipeline
# ---------------------------------------------------------------------------


def _build_graph(openrouter_key: str, tavily_key: str):
    """Build and return the compiled LangGraph graph. Called once per warm start."""
    from langchain_core.messages import HumanMessage, SystemMessage
    from langchain_openai import ChatOpenAI
    from langchain_tavily import TavilySearch
    from langgraph.graph import END, StateGraph

    llm = ChatOpenAI(
        model=os.environ.get("OPENROUTER_MODEL", "openai/gpt-5.4-nano"),
        openai_api_key=openrouter_key,
        openai_api_base="https://openrouter.ai/api/v1",
        temperature=0.4,
    )

    _SYSTEM_PROMPT = _PROMPTS_ENV.get_template("system.j2").render()

    search_tool = TavilySearch(
        tavily_api_key=tavily_key,
        max_results=int(os.environ.get("TAVILY_MAX_RESULTS", "10")),
        search_depth=os.environ.get("TAVILY_SEARCH_DEPTH", "advanced"),
        topic=os.environ.get("TAVILY_TOPIC", "finance"),
        time_range=os.environ.get("TAVILY_TIME_RANGE") or None,
    )
    search_workers = int(os.environ.get("TAVILY_SEARCH_WORKERS", "5"))

    class AgentState(TypedDict):
        snippets: list[str]
        queries: list[str]
        search_results: list[dict]
        report: str

    # --- Node: Query Generation ---
    def query_generation_node(state: AgentState) -> AgentState:
        snippets_text = "\n\n---\n\n".join(state["snippets"])
        prompt = _PROMPTS_ENV.get_template("query_generation.j2").render(
            snippets_text=snippets_text
        )
        response = llm.invoke([SystemMessage(content=_SYSTEM_PROMPT), HumanMessage(content=prompt)])
        lines = [
            line.lstrip("0123456789. ").strip()
            for line in response.content.strip().splitlines()
            if line.strip()
        ]
        return {**state, "queries": lines}

    # --- Node: Web Search ---
    def web_search_node(state: AgentState) -> AgentState:
        all_results = []
        with ThreadPoolExecutor(max_workers=search_workers) as pool:
            futures = {pool.submit(search_tool.invoke, {"query": q}): q for q in state["queries"]}
            for future in as_completed(futures):
                query = futures[future]
                try:
                    result = future.result()
                    for r in result.get("results", []):
                        all_results.append(
                            {
                                "query": query,
                                "content": r.get("content", ""),
                                "url": r.get("url", ""),
                            }
                        )
                except Exception:
                    pass  # single-query failures should not abort the entire run
        return {**state, "search_results": all_results}

    # --- Node: Market Analyst ---
    def market_analyst_node(state: AgentState) -> AgentState:
        today = _today_utc()
        snippets_text = "\n\n---\n\n".join(state["snippets"])
        context_parts = [
            f"**Query:** {r['query']}\n**Source:** {r['url']}\n{r['content']}"
            for r in state["search_results"]
        ]
        context_text = "\n\n---\n\n".join(context_parts)
        prompt = _PROMPTS_ENV.get_template("market_analyst.j2").render(
            today=today,
            snippets_text=snippets_text,
            context_text=context_text,
        )
        response = llm.invoke([SystemMessage(content=_SYSTEM_PROMPT), HumanMessage(content=prompt)])
        report_md = (
            f"# Investment News Analysis AI — {today}\n\n"
            f"{response.content.strip()}\n\n"
            f"---\n*Generated by Investment News Analysis AI v{INA_VERSION}*"
        )
        return {**state, "report": report_md}

    # --- Graph assembly ---
    graph = StateGraph(AgentState)
    graph.add_node("query_generation", query_generation_node)
    graph.add_node("web_search", web_search_node)
    graph.add_node("market_analyst", market_analyst_node)

    graph.set_entry_point("query_generation")
    graph.add_edge("query_generation", "web_search")
    graph.add_edge("web_search", "market_analyst")
    graph.add_edge("market_analyst", END)

    return graph.compile()


# Cache the compiled graph across warm Lambda invocations
_graph = None


# ---------------------------------------------------------------------------
# Lambda handler
# ---------------------------------------------------------------------------


def handler(event, context):
    today = _today_utc()
    print(f"[agent] Starting run for {today}")

    snippets = _list_snippets(today)

    if not snippets:
        print("[agent] No snippets found — generating fallback report")
        md_text = _no_snippets_report(today)
    else:
        print(f"[agent] Found {len(snippets)} snippet(s) — running LangGraph pipeline")
        openrouter_key = _get_secret(SSM_OPENROUTER_PARAM)
        tavily_key = _get_secret(SSM_TAVILY_PARAM)

        global _graph
        if _graph is None:
            _graph = _build_graph(openrouter_key, tavily_key)

        initial_state = {
            "snippets": snippets,
            "queries": [],
            "search_results": [],
            "report": "",
        }
        final_state = _graph.invoke(initial_state)
        md_text = final_state["report"]

    pdf_bytes = _md_to_pdf(md_text)
    _upload_report(today, md_text, pdf_bytes)
    print(f"[agent] Report uploaded to s3://{OUTPUT_BUCKET}/output/{today}/")

    return {"statusCode": 200, "date": today}
